version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: finance-control-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: finance_control_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  postgres_data: